---
title: "Navigo - Agents"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load files

```{r cars}
nasa_tlx <- read.csv("../results/nasa_tlx.csv", stringsAsFactors = FALSE)
decision_points <- read.csv("../results/decision_points.csv", stringsAsFactors = FALSE)
post_trial <- read.csv("../results/post_trial.csv", stringsAsFactors = FALSE)
```

## NASA TLX

### Pure Conditions

```{r pressure, echo=FALSE}
text_color = paletteer_d(ghibli, MarnieLight1)[2]

nasa_tlx %>% 
  select(subject, pd.total, po.total, pe.total) %>% 
  melt(id("subject")) %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(alpha = .7, width = .25, height = .25) + 
  aes(col = variable) +
  scale_color_discrete(guide = FALSE) + 
  geom_boxplot(aes(fill = variable), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  labs(title = "NASA TLX Scores for pure conditions",
       x = "",
       y = "NASA TLX Score") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```

### Driver Model factorial conditions

```{r}
nasa_tlx %>% 
  select(subject, pd.total, do.total, de.total, od.total, ed.total) %>% 
  melt(id("subject")) %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(alpha = .7, width = .25, height = .25) + 
  aes(col = variable) +
  scale_color_brewer(palette = "Set2", guide = FALSE) + 
  geom_boxplot(aes(fill = variable), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  scale_fill_brewer(palette = "Set2", guide = FALSE) +
  labs(title = "NASA TLX Scores for Driver conditions",
       x = "",
       y = "NASA TLX Score") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```

### Explorer Conditions

```{r}
nasa_tlx %>% 
  select(subject, pe.total, ed.total, eo.total, de.total, oe.total) %>% 
  melt(id("subject")) %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(alpha = .7, width = .25, height = .25) + 
  aes(col = variable) +
  scale_color_discrete(guide = FALSE) + 
  geom_boxplot(aes(fill = variable), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  labs(title = "NASA TLX Scores for Explorer conditions",
       x = "",
       y = "NASA TLX Score") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```

### Optimal Conditions

```{r}
nasa_tlx %>% 
  select(subject, po.total, od.total, oe.total, do.total, eo.total) %>% 
  melt(id("subject")) %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(alpha = .7, width = .25, height = .25) + 
  aes(col = variable) +
  scale_color_discrete(guide = FALSE) + 
  geom_boxplot(aes(fill = variable), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  labs(title = "NASA TLX Scores for Optimal conditions",
       x = "",
       y = "NASA TLX Score") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```

### Impact on Deviations

```{r}
decision_points %>% 
  select(subject, task, devratio) %>% 
  filter(devratio > 0.0) %>% 
  ggplot(aes(x = task, y = devratio)) +
  geom_jitter(alpha = .7, width = .25, height = 0) + 
  aes(col = task) +
  scale_color_discrete(guide = FALSE) + 
  geom_boxplot(aes(fill = task), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  labs(title = "Deviation Ratio per Condition",
       subtitle = "Only included drives with >0 deviations",
       x = "",
       y = "Deviation Ratio") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```

```{r}
decision_points %>% 
  select(subject, choice, devratio) %>% 
  filter(devratio > 0.0) %>% 
  ggplot(aes(x = choice, y = devratio)) +
  geom_jitter(alpha = .7, width = .25, height = 0) + 
  aes(col = choice) +
  scale_color_discrete(guide = FALSE) + 
  geom_boxplot(aes(fill = choice), colour = text_color, show.legend = FALSE, 
               outlier.shape = NA, alpha = 0.4) +
  labs(title = "Deviation Ratio per Choice",
       subtitle = "Only included drives with >0 deviations",
       x = "",
       y = "Deviation Ratio") +
  theme_tufte(base_family = "Avenir", ticks = FALSE)
```



